# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Send email report
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  send-email-report:
    runs-on: ubuntu-latest
    steps:
      - name: Send email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: 'Daily report'
          body: 'Daily report attached'
          to: ${{ secrets.EMAIL }}
          from: ${{ secrets.EMAIL }}
          attachments: deploy-report.txt